#设置国内镜像
options()$repos 
options()$BioC_mirror
options(BioC_mirror="https://mirrors.ustc.edu.cn/bioc/")
options(BioC_mirror="https://mirrors.tuna.tsinghua.edu.cn/bioconductor/")
options("repos" = c(CRAN="https://mirrors.tuna.tsinghua.edu.cn/CRAN/"))
options(BioC_mirror="https://mirrors.westlake.edu.cn/bioconductor")
utils::setRepositories(ind=1:2)
options()$repos 
options()$BioC_mirror

#如果下载不下来，就去网站下载下来，本地安装
#' 包的安装
install.packages("devtools","remotes","BiocManager")
install.packages(c('tibble','plyr','pacman','ggplot2','ggpubr','RColorBrewer','tuneR','readr','progress','dplyr','data.table','magrittr','ggplotify',"purrr","linkET","correlate","corrplot","psych","GGally",
                   'stringr','reshape2','tidyr','ggsignif','ggrepel','ggthemes','ggsci','ggExtra','ggforce','cowplot','patchwork',"aplot","ggalign","ggsankey"))
install.packages(c('WGCNA','e1071', 'preprocessCore',"ppcor",  "timeROC", "pracma",'survival', 'survminer',"caret",'pROC','umap',"clustree","rstatix","harmony"))
install.packages(c("FactoMineR", "factoextra","XML","glmnet","maxstat","rvest","caret","pheatmap","ComplexHeatmap","circlize","ggdendro","ggtree","igraph",
                   "ggraph","tidygraph","tidytext","tidyverse","plotly","shiny","shinyjs","shinyBS","shinyWidgets",
                   "shinycssloaders","shinythemes","DT","visNetwork","networkD3","DiagrammeR",
                   "rmarkdown","knitr"))

devtools::install_github("GfellerLab/EPIC", build_vignettes=TRUE)
devtools::install_github("IOBR/IOBR", build_vignettes=TRUE)
devtools::install_github("GreenleafLab/chromVARmotifs")
devtools::install_github("digitalcytometry/cytotrace2", subdir = "cytotrace2_r")
devtools::install_github("GreenleafLab/ArchR", ref="master", repos = BiocManager::repositories())
devtools::install_github("immunogenomics/presto")
remotes::install_github('chris-mcginnis-ucsf/DoubletFinder', force = TRUE)
devtools::install_github("immunogenomics/harmony", build_vignettes=TRUE)
devtools::install_github('satijalab/seurat-data')
remotes::install_github('satijalab/seurat-wrappers')
remotes::install_github("mojaveazure/seurat-disk")
devtools::install_github("aertslab/SCopeLoomR")
devtools::install_github('mojaveazure/loomR')
devtools::install_github('smorabit/hdWGCNA', ref='dev')
devtools::install_github("velocyto-team/velocyto.R")

#下载到服务器，然后用install_local()来安装
devtools::install_local("PATH/TO/DIRECTORY/CytoTRACE_0.3.3.tar.gz")
# https://bioconductor.org/packages/release/bioc/html/GEOquery.html
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("KEGGREST","dittoSeq","scCustomize"),ask = F,update = F)
BiocManager::install(c("GSEABase","GSVA","clusterProfiler","GenomicRanges","GenomicFeatures","GenomicAlignments"),ask = F,update = F)
BiocManager::install(c("GEOquery","limma","impute" ),ask = F,update = F)
BiocManager::install(c("genefu","org.Hs.eg.db","org.Mm.eg.db","hgu133plus2.db" ),ask = F,update = F)
BiocManager::install(c('airway','DESeq2','edgeR'),ask = F,update = F)
BiocManager::install(c('scran'),ask = F,update = F)
BiocManager::install(c("TxDb.Mmusculus.UCSC.mm10.knownGene","TxDb.Mmusculus.UCSC.mm39.knownGene","org.Mm.eg.db","TxDb.Hsapiens.UCSC.hg38.knownGene"),ask = F,update = F)
BiocManager::install(c('Seurat','monocle'),ask = F,update = F)
BiocManager::install(c('destiny','scRNAseq','dbscan','M3Drop','flexclust','mcclust'),ask = F,update = F)
BiocManager::install(c("biomaRt","sva","GO.db"),ask = F,update = F)
BiocManager::install(c('monocle3','Signac',"cicero","JASPAR2020","TFBSTools",
                       "BSgenome.Hsapiens.UCSC.hg38","BSgenome.Mmusculus.UCSC.mm39","EnsDb.Mmusculus.v79","EnsDb.Hsapiens.v86","chromVAR",
                       "ChIPseeker","SingleCellExperiment","NMF","scater","SC3"),ask = F,update = F)
BiocManager::install(c("motifmatchr"),ask = F,update = F)
BiocManager::install(c("ggtreeExtra","ggtree","ggtreeAssist","ggtreeify","ggtreeLayout","ggtreeify","ggtreeDendro","ggtreeGrob"),ask = F,update = F)
BiocManager::install("progeny","AUCell")    
BiocManager::install("kstreet13/slingshot")
BiocManager::install("pcaMethods")
library(ArchR)
library(Signac)
library(cicero)
library(data.table)
library(dplyr)
library(Matrix)
library(ggplot2)
library(scCustomize)
library(clustree)
library(ROGUE)
library(recall)
library(Seurat)
library(patchwork)
library(dittoSeq)
library(scales)
library(umap)
library(factoextra)
library(FactoMineR)
library(RColorBrewer)
library(JASPAR2020)
library(TFBSTools)
library(chromVARmotifs)
data("human_pwms_v2")
library(BSgenome.Hsapiens.UCSC.hg38)
library(patchwork)
library(EnsDb.Hsapiens.v86)
library(chromVAR)
library(rstatix)
library(org.Hs.eg.db)
library(data.table)
library(dittoSeq)
library(scCustomize)
library(Seurat)
library(CytoTRACE)
library(CytoTRACE2)
library(stringr)
library(ChIPseeker)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(TxDb.Mmusculus.UCSC.mm39.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg38.knownGene
library(tidytext)
library(GenomicRanges)
library(GenomicFeatures)
library(foreach)
library(doParallel)
library(data.table)
library(dplyr)
library(tibble)
library(ComplexHeatmap)
library(SC3)
library(future)
library(patchwork)
library(cowplot)
library(ggsci)
library(NMF)
library(SingleCellExperiment)
library(scater)
library(DoubletFinder)
library(RColorBrewer)
library(magrittr)
library(forcats)
library(aplot)
library(ggalign)
library(ClusterGVis)






